
import Icon from "react-native-vector-icons/FontAwesome";

export default {
  LIGHT_GRAY: "#EDEDED",
  PRIMARY: "#9f5bff",
  WHITE: "#FFF",
  BLACK: "#000000",
  YELLOW: "yellow",
};

/* fonts */
export const FontFamily = {
  textStyleSmallTextRegular: "Poppins-Regular",
  buttone16pxS: "Gilroy",
  crimsonTextRegular: "CrimsonText-Regular",
  textStyleSmallTextBold: "Poppins-SemiBold",
  interExtraBold: "Inter-ExtraBold",
  interRegular: "Inter-Regular",
  textStyleSmallerTextSemiBold: "Poppins-Medium",
  interMedium: "Inter-Medium",
  poppinsBold: "Poppins-Bold",
  gilroyBold: "Gilroy-Bold",
  radleyRegular: "Radley-Regular",
  gilroyMedium: "Gilroy-Medium",
  soraRegular: "Sora-Regular",
  soraSemiBold: "Sora-SemiBold",
   gilroyBold: 'Gilroy-Bold',
  gilroySemiBold: 'Gilroy-SemiBold',
  gilroyMedium: 'Gilroy-Medium',
  gilroyRegular: 'Gilroy-Regular',
   regular: "Roboto-Regular",
  medium: "Roboto-Medium",
  bold: "Roboto-Bold",
};

/* font sizes */
export const FontSize = {
  size_smi: 13,
  buttone16pxS_size: 18,
  textStyleSmallTextBold_size: 14,
  textStyleSmallerTextSemiBold_size: 11,
  size_6xl: 25,
  size_3xs: 10,
  size_xs: 12,
  textStyleNormalTextBold_size: 16,
  textStyleNormalTextBold_size2: 14,
  textStyleNormalTextBold_size1: 18,
  textStyleLargeTextBold_size: 20,
  size_6xs: 7,
  textStyleSmallerTextSmallLabel_size: 8,
   size_xs: 12,
  size_sm: 14,
  size_md: 16,
  size_lg: 18,
  size_xl: 22,
    small: 13,
  medium: 16,
  H4: 20,
};
/* Colors */
export const Color = {
  blue: "#007bff",
  white0: "#ffffff",
  colorSnow: "#fdf3f3",
  colorGray_100: "#939393",
  colorGray_200: "#808080",
  colorGray_300: "#7c7c7c",
  colourStylesNeutralColourGray2: "#797979",
  colorGray_400: "#181725",
  colourStylesLabelColour: "#000",
  colorTomato: "#ff4747",
  colourStylesSecondaryColourSecondary20: "#ffe1b3",
  colourStylesNeutralColourBlack: "#000",
  colorDimgray: "#666",
  colourStylesPrimaryColourPrimary80: "#71b1a1",
  colourStylesNeutralColourGray1: "#484848",
  colorDarkslategray_100: "#303336",
  colorLightyellow: "#ffffffee1",
  colorChocolate: "#e97639",
  colourStylesPrimaryColourPrimary40: "#dbebe7",
  colorGainsboro_100: "#ddd",
  colourStylesNeutralColourGray4: "#d9d9d9",
  colorFirebrick: "#b32525",
  colourStylesNeutralColourGray3: "#a9a9a9",
  colorWhitesmoke_100: "#f3f3f3",
  colorWhitesmoke_200: "#eaeaea",
  colorGhostwhite: "#ffffff9ff",
  colorMediumseagreen: "#36c07e",
  colourStylesPrimaryColourPrimary100: "#129575",
  colordarkred: "#8b0000",
  colorlightbutton: "rgb(230, 183, 129)",
  background: "#e6c29e",
  white: "#FFFFFF",
  black: "#000000",
  lightGrey: "#E0E0E0",
  greyText: "#777",
  darkText: "#222",
  inputBackground: "#F9F9F9",
  error: "#D32F2F",
  primaryGold: "#C59D5F", // Your theme color
  red:"red",
  footer:"rgba(252, 198, 147, 0.9)",
};

/* Paddings */
export const Padding = {
  p_6xs: 7,
  p_10xs: 3,
  p_xl: 20,
  p_13xl: 32,
  p_3xs: 10,
  p_11xl: 30,
  p_8xs: 5,
  p_xs: 12,
  p_5xs: 8,
  p_9xs_5: 4,
};
/* border radiuses */
export const Border = {
  br_mini: 15,
  br_11xl: 30,
  br_xl: 20,
  br_smi: 13,
  br_3xs: 10,
  br_5xs: 8,
  br_9xs: 4,
  br_sm: 14,
  br_6xs: 7,
  br_12xs_5: 1,
  br_31xl: 50,
  br_lgi: 19,
  br_xs: 12,
  br_10xs_5: 3,
   br_sm: 6,
  br_md: 10,
};



